-- STUVA SUPABASE SCHEMA
-- Run this in your Supabase SQL Editor

-- 1. Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  phone text UNIQUE NOT NULL,
  name text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Kitchens Table
CREATE TABLE IF NOT EXISTS public.kitchens (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  slug text UNIQUE NOT NULL,
  name text NOT NULL,
  rating numeric DEFAULT 0,
  delivery_time text,
  description text,
  image_url text,
  is_active boolean DEFAULT true,
  subscription_expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Addresses Table
CREATE TABLE IF NOT EXISTS public.addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  apartment text NOT NULL,
  area text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Menu Items Table
CREATE TABLE IF NOT EXISTS public.menu_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  kitchen_id uuid REFERENCES public.kitchens(id) ON DELETE CASCADE,
  name text NOT NULL,
  price numeric NOT NULL,
  available boolean DEFAULT true,
  category text,
  thali_type text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Orders Table (THE MISSING ONE)
CREATE TABLE IF NOT EXISTS public.orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  kitchen_id uuid REFERENCES public.kitchens(id) ON DELETE SET NULL,
  customer_name text,
  customer_phone text,
  total numeric NOT NULL,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text DEFAULT 'pending',
  address jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Kitchen Admins Table
CREATE TABLE IF NOT EXISTS public.kitchen_admins (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  kitchen_id uuid REFERENCES public.kitchens(id) ON DELETE CASCADE,
  phone text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- --- Enable RLS ---
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kitchens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kitchen_admins ENABLE ROW LEVEL SECURITY;

-- --- Public Access Policies (Simplification for prototype) ---
CREATE POLICY "Public read users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public write users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update users" ON public.users FOR UPDATE USING (true);

CREATE POLICY "Public read kitchens" ON public.kitchens FOR SELECT USING (true);

CREATE POLICY "Public read addresses" ON public.addresses FOR SELECT USING (true);
CREATE POLICY "Public write addresses" ON public.addresses FOR INSERT WITH CHECK (true);

CREATE POLICY "Public read menu" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Public write menu" ON public.menu_items FOR ALL USING (true);

CREATE POLICY "Public read orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Public write orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update orders" ON public.orders FOR UPDATE USING (true);

CREATE POLICY "Public read admins" ON public.kitchen_admins FOR SELECT USING (true);
